CREATE TABLE tb_usuario (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user" VARCHAR(100) NOT NULL,
    senha  VARCHAR(255) NOT NULL,
    role   VARCHAR(20)  NOT NULL,

    CONSTRAINT uk_usuario_user UNIQUE ("user")
);

CREATE TABLE tb_leilao (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo    VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    status    VARCHAR(20)  NOT NULL
);

CREATE TABLE tb_patio (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(100) NOT NULL,
    endereco  VARCHAR(255) NOT NULL,
    leilao_id BIGINT NOT NULL,

    CONSTRAINT fk_patio_leilao
        FOREIGN KEY (leilao_id) REFERENCES tb_leilao (id) ON DELETE RESTRICT
);

CREATE INDEX idx_patio_leilao_id ON tb_patio (leilao_id);

CREATE TABLE tb_horario_visita (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora          TIMESTAMP NOT NULL,
    vagas_totais       INTEGER NOT NULL,
    vagas_disponiveis  INTEGER NOT NULL,
    patio_id           BIGINT NOT NULL,

    CONSTRAINT fk_horario_visita_patio
        FOREIGN KEY (patio_id) REFERENCES tb_patio (id) ON DELETE RESTRICT,

    CONSTRAINT ck_horario_visita_vagas_nao_negativas
        CHECK (vagas_disponiveis >= 0),

    CONSTRAINT ck_horario_visita_vagas_disponiveis_limite
        CHECK (vagas_disponiveis <= vagas_totais)
);

CREATE INDEX idx_horario_visita_patio_id ON tb_horario_visita (patio_id);
CREATE INDEX idx_horario_visita_data_hora ON tb_horario_visita (data_hora);

CREATE TABLE tb_visitante (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(150) NOT NULL,
    cgc       VARCHAR(20)  NOT NULL,
    email     VARCHAR(150) NOT NULL,
    telefone  VARCHAR(20)  NOT NULL,

    CONSTRAINT uk_visitante_cgc UNIQUE (cgc)
);

CREATE TABLE tb_agendamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_registro  TIMESTAMP,
    status         VARCHAR(20) NOT NULL,
    horario_id     BIGINT NOT NULL,
    visitante_id   BIGINT NOT NULL,

    CONSTRAINT fk_agendamento_horario
        FOREIGN KEY (horario_id) REFERENCES tb_horario_visita (id) ON DELETE RESTRICT,

    CONSTRAINT fk_agendamento_visitante
        FOREIGN KEY (visitante_id) REFERENCES tb_visitante (id) ON DELETE RESTRICT,

    CONSTRAINT uk_agendamento_visitante_horario
        UNIQUE (visitante_id, horario_id)
);

CREATE INDEX idx_agendamento_horario_id ON tb_agendamento (horario_id);
CREATE INDEX idx_agendamento_visitante_id ON tb_agendamento (visitante_id);
CREATE INDEX idx_agendamento_status ON tb_agendamento (status);