spring.datasource.url=jdbc:postgresql://localhost:5432/visitaja_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

spring.config.import=optional:file:.env[.properties]